### ISSUE TITLE
Split theme based plugins into their own section

### ISSUE THREAD

**Issue by DogmaDragon** [feederbox826/dogma-docs#1]
After thinking about this more and after adding a bunch of plugins, I found that themes don't cleanly integrate into the same list as general plugins. Especially those that lack word theme in the name or big theme collections that have multiple plugin dependencies.

I would love to have either a separate or modified build task that creates 2 .md files, one for themes and one for plugins. 

The structure would be the same.

**Comment by feederbox826** [comment]
Sorry, just revisiting this now. Having a hard time trying to conceptualize the split between theme and plugins... Will try making progress today

**Comment by feederbox826** [comment]
https://github.com/feederbox826/dogma-docs/commit/b3ff4a5dc892ced4247f78317472f290825972bb
