### ISSUE TITLE
Collections that use exclusive gets scripts duplicated

### ISSUE THREAD

**Issue by DogmaDragon** [feederbox826/dogma-docs#2]
Collections that use `exclusive: true` gets scripts duplicated if a new item gets added to the index, but is not defined in the collection. 

![image](https://github.com/feederbox826/dogma-docs/assets/103123951/2734dc05-52ca-4899-890f-5eb604d6a319)

Would be potentially fixed by https://github.com/feederbox826/dogma-docs/issues/1.

**Comment by feederbox826** [comment]
This is a seperate issue from #1, exclusive should not add any new items from the index :/

**Comment by feederbox826** [comment]
https://github.com/feederbox826/dogma-docs/blob/2322085a61d52960139eec70043c6aece315d88c/builder/build.ts#L84-L86
